source 'http://rubygems.org'
ruby '1.9.3'

gem 'sinatra'
gem 'sinatra_more'
gem 'bourbon'
gem 'sass'
gem 'haml'
gem 'thin'
gem 'heroku'
gem 'pg'
gem 'data_mapper'
gem 'dm-is-sluggable'
gem 'dm-constraints'
gem 'redcarpet'
gem 'coderay'
gem 'json'
gem 'tux'
gem 'foreman'
gem 'gemoji'
gem 'faker'
gem 'newrelic_rpm'

group :production do
  gem 'dm-postgres-adapter'
end

group :development, :test do
  gem 'rake'
  gem 'guard'
  gem 'guard-sass'
  gem 'guard-coffeescript'
  gem 'guard-livereload'
  gem 'rerun'
  gem 'rb-fsevent', '~> 0.9.1'
  gem 'dm-sqlite-adapter'
  gem 'minitest'
  gem 'minitest-stub-const'
  gem 'minitest-colorize'
  gem 'mocha'
  gem 'database_cleaner'
  gem 'shoulda-context'
  gem 'factory_girl'
end
